package com.quimera.model;

/**
 * Created by Manu on 11/3/16.
 */
public enum TriviaStatus {

    RUNNABLE, READY, TERMINATED,
    SHOWING_PARTIAL_WINNERS, SHOWING_FINAL_WINNERS, SHOWING_QUESTION, SHOWING_OPTIONS,
    SHOWING_CORRECT_ANSWER, SHOWING_BANNER, SHOWING_DESCRIPTION

}
